# 主域名 https 服务
server {
    # certbot设置自动证书会自动配置的
    listen 443 ssl http2 default_server;
    server_name jiang-xia.top;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_certificate /etc/letsencrypt/live/jiang-xia.top/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/jiang-xia.top/privkey.pem; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    root /opt/jxapp/front/;
    include /etc/nginx/default.d/*.conf;   # 保留原include

    location / {
        proxy_pass http://localhost:5050/;
    }
    location /zone/ {
        alias /opt/jxapp/front/zone/;
        try_files $uri $uri/ /zone/index.html;
        index index.html index.htm;
    }
    location /admin/xia-admin/ {
        alias /opt/jxapp/front/xia-admin/;
        try_files $uri $uri/ /admin/xia-admin/index.html;
        index index.html index.htm;
    }

    ### blog-server 后端api地址反向代理 ###
    location /x-blog/api/v1/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;  #获取客户端真实IP
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # 如当burst=5，表示当请求超过限定速率时，允许超出的请求数量为5，这5个请求会阻塞等待，以限定速率依次通过。
        limit_req zone=perip burst=20 nodelay; #漏桶数为５个．也就是队列数．nodelay:不启用延迟．
        proxy_pass http://localhost:5000/api/v1/;
    }
    location /x-blog/api/v1/doc/ {
        proxy_pass http://localhost:5000/api/v1/doc/;
    }
    # 兼容之前已经上传的静态资源图片
    location /x-api/blog-server/static/ {
        proxy_pass http://localhost:5000/static/;
    }
    # 新的文件上传地址
    location /x-blog/api/v1/static/ {
        proxy_pass http://localhost:5000/static/;
    }

    ### zone-server 后端api地址反向代理 ###
    # zone wss 升级接口wss websocket发起房自身也需要是https环境
    location /x-zone/api/v1/mobile/chat {
        proxy_pass http://localhost:9600/api/v1/mobile/chat;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 600s;  
    }
    # zone api 转发
    location /x-zone/api/v1/ {
        limit_req zone=perip burst=20 nodelay; 
        proxy_pass http://localhost:9600/api/v1/;
    }
    location /x-zone/api/v1/swagger/index.html {
        proxy_pass http://localhost:9600/api/v1/swagger/index.html;
        index  index.html index.htm;
    }
    # gin-zone 项目文件服务器
    location /x-zone/api/v1/public/ {
        proxy_pass http://localhost:9600/public/;
    }
    # location用法解释：https://blog.csdn.net/qq_37568918/article/details/121167951
    error_page 404 /404.html;
    location = /40x.html {}

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {}
}

# 主域名 http 重定向
server {
    listen 80;
    server_name jiang-xia.top;
    return 301 https://$host$request_uri;
}