# /etc/nginx/conf.d/main.conf
# 限速区域
limit_req_zone  $binary_remote_addr  zone=perip:10m   rate=20r/s;

# gzip 配置
gzip on;
gzip_buffers 32 4K;
gzip_comp_level 6;
gzip_min_length 1024;
gzip_types application/javascript text/javascript text/css text/xml;
gzip_disable "MSIE [1-6]\.";
gzip_vary on;