export const publicKey = `
-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL9r8jKkfORpiunFylF4XwvNi06sTD3N
4hYLAmGNmviZ1IhCnu4VZ0sShdj7LYfh/Rw5IuqY55XXr6zVB/LzQ70CAwEAAQ==
-----END PUBLIC KEY-----
`;
export const privateKey = `
-----BEGIN PRIVATE KEY-----
MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEAv2vyMqR85GmK6cXK
UXhfC82LTqxMPc3iFgsCYY2a+JnUiEKe7hVnSxKF2Psth+H9HDki6pjnldevrNUH
8vNDvQIDAQABAkEAi6NzSv4zHWzgqShgLo5gx3tp5DpMY8mM5Aej9QYXxsEtzq/+
oTPfooVF2rX4rE8NwTpNzwIfzOnrCw5vVCm1AQIhAOZalT7Rx1bqg6irko6MDkVk
9rKW7jebRZ7i3JbonM9DAiEA1Lu9aUWAb98pNRTBnszVzj9FGZKjlSrW/f/PWN2m
8P8CIQCXFFwESoQKDl9xda32jgciHljqwrDUiaL81V/GHiQSjwIgFApzt50ikmd1
nFiOPQWTBtETE2urGXxlsJwOzpJjDcUCIQCV4z96GjcuMYH92dVhmLKFC0ZRX30A
mO+bs1CWyhWG0g==
-----END PRIVATE KEY-----
`;

// 客户端公钥
export const clientPublicKey = `
-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMbhQdr30GxvE3SYAJVILYLo7/6XqAnm
5hHesj5X+Ub76s45DBuI3ip+qIsnFKMaX8gKDYcUzqiKDjeOJLD/910CAwEAAQ==
-----END PUBLIC KEY-----
`;
